In [15]:
import pandas as pd
import numpy as np

In [19]:
import pandas as pd

# Load the file to inspect its content
file_path = r'D:\xjtufiles\3ee\DGA_data_pre.csv'
df = pd.read_csv(file_path)

# Display the first few rows of the dataframe to understand its structure
df.head()


h2     ch4  c2h6    c2h4    c2h2  act
0   294.00   27.40   5.6   52.60  338.00    1
1   200.83   59.45  41.0   40.48  150.84    1
2    71.60   20.20   2.7   34.60   44.20    1
3    29.30   24.90   7.3   11.40    7.50    1
4  1170.00  255.00  18.0  312.00  325.00    1

In [20]:
df

h2     ch4    c2h6    c2h4     c2h2  act
0      294.00   27.40   5.600   52.60  338.000    1
1      200.83   59.45  41.000   40.48  150.840    1
2       71.60   20.20   2.700   34.60   44.200    1
3       29.30   24.90   7.300   11.40    7.500    1
4     1170.00  255.00  18.000  312.00  325.000    1
...       ...     ...     ...     ...      ...  ...
1430   980.00   73.00  58.000   12.00    0.000    6
1431    44.63   35.36   7.590    1.68    0.000    6
1432   743.00   74.00  39.000    6.00    0.000    6
1433   106.00    4.00   2.000    1.00    0.001    6
1434   235.00   16.00   0.001   35.00    0.001    6

[1435 rows x 6 columns]

In [21]:
# df = pd.read_csv(r'D:\xjtufiles\3ee\DGA_data_pre.csv', index_col = 0)
df = df.iloc[:-1,:]
# df

df['h2'] = pd.to_numeric(df['h2'],errors='coerce')
df['ch4'] = pd.to_numeric(df['ch4'],errors='coerce')
df['c2h6'] = pd.to_numeric(df['c2h6'],errors='coerce')
df['c2h4'] = pd.to_numeric(df['c2h4'],errors='coerce')
df['c2h2'] = pd.to_numeric(df['c2h2'],errors='coerce')
df['act'] = pd.to_numeric(df['act'],errors='coerce')

#df.dtypes

C:\Users\11094\AppData\Local\Temp\ipykernel_19316\2593832488.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['h2'] = pd.to_numeric(df['h2'],errors='coerce')
C:\Users\11094\AppData\Local\Temp\ipykernel_19316\2593832488.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ch4'] = pd.to_numeric(df['ch4'],errors='coerce')
C:\Users\11094\AppData\Local\Temp\ipykernel_19316\2593832488.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_inde

In [22]:
df = df.reset_index(drop=True) #reset index

In [23]:
print(df['act'].nunique(dropna=True)) # 显示类别数量

6


In [24]:
X = df.iloc[:, :5]
y = df.iloc[:, -1]


In [25]:
# 划分训练集和测试集
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.10, random_state=42)

In [26]:
# 使用 KNN 进行分类
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 1)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [27]:
# 评估 KNN 模型
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[21  4  2  0  1  0]
 [ 2 40  0  0  1  0]
 [ 3  1 13  1  0  1]
 [ 1  1  1 16  1  1]
 [ 0  4  0  2 16  0]
 [ 1  0  0  0  0 10]]
Classification Report:
              precision    recall  f1-score   support

           1       0.75      0.75      0.75        28
           2       0.80      0.93      0.86        43
           3       0.81      0.68      0.74        19
           4       0.84      0.76      0.80        21
           5       0.84      0.73      0.78        22
           6       0.83      0.91      0.87        11

    accuracy                           0.81       144
   macro avg       0.81      0.79      0.80       144
weighted avg       0.81      0.81      0.80       144

Accuracy: 0.8055555555555556


In [28]:
from xgboost.sklearn import XGBClassifier

xgb1 = XGBClassifier(
 learning_rate =0.05,
 n_estimators=700,
 max_depth=6,
 min_child_weight=1,
 gamma=0,
 subsample=0.8,
 colsample_bytree=0.8,
 objective= 'multi:softprob',
 nthread=8,
 scale_pos_weight=2,
 seed=27)


In [29]:
y_train = y_train - 1
y_test = y_test - 1

In [30]:
xgb1.fit(X_train,y_train)

C:\Users\11094\AppData\Roaming\Python\Python310\site-packages\xgboost\core.py:158: UserWarning: [13:23:09] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-08cbc0333d8d4aae1-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "scale_pos_weight" } are not used.

  warnings.warn(smsg, UserWarning)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=0, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=700, n_jobs=None, nthread=8,
              num_parallel_tree=None, ...)

In [31]:
preds = xgb1.predict(X_test) # 输出类别

In [32]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(preds,y_test) # 计算准确率
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 77.08%


In [33]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, preds)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, preds)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,preds)
print("Accuracy:",result2)

Confusion Matrix:
[[20  3  5  0  0  0]
 [ 2 41  0  0  0  0]
 [ 7  2  9  1  0  0]
 [ 0  1  0 17  1  2]
 [ 1  4  0  3 14  0]
 [ 0  1  0  0  0 10]]
Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.71      0.69        28
           1       0.79      0.95      0.86        43
           2       0.64      0.47      0.55        19
           3       0.81      0.81      0.81        21
           4       0.93      0.64      0.76        22
           5       0.83      0.91      0.87        11

    accuracy                           0.77       144
   macro avg       0.78      0.75      0.76       144
weighted avg       0.77      0.77      0.76       144

Accuracy: 0.7708333333333334


通常情况下，训练数据和测试数据的标准化应该使用相同的均值和标准差。因此，标准化测试数据时应使用 scaler.transform(X_test) 而不是 scaler.fit_transform(X_test)。这样可以确保训练数据和测试数据使用相同的标准化参数。

In [34]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_ts = scaler.fit_transform(X_train)
X_tes = scaler.transform(X_test)
classifier.fit(X_ts,y_train)

KNeighborsClassifier(n_neighbors=1)

In [35]:
y_tes = classifier.predict(X_tes)

In [36]:
accuracy = accuracy_score(y_tes,y_test)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 80.56%


In [37]:
leaf_size = list(range(1,50))
n_neighbors = list(range(1,30))
p=[1,2]
hyperparameters = dict(leaf_size=leaf_size, n_neighbors=n_neighbors, p=p)

knn_2 = KNeighborsClassifier()

from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(knn_2, hyperparameters, cv=10)

clf = GridSearchCV(knn_2, hyperparameters, cv=10)

clf.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'leaf_size': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                       13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                       23, 24, 25, 26, 27, 28, 29, 30, ...],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29],
                         'p': [1, 2]})

In [38]:
y_t = clf.predict(X_test)
accuracy = accuracy_score(y_t,y_test)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 73.61%


In [39]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

clf = RandomForestClassifier(max_depth=13, random_state=42)

clf.fit(X_train, y_train)

y_t = clf.predict(X_test)

In [40]:
accuracy = accuracy_score(y_t,y_test)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 81.25%


In [41]:
for i in range(1,20):
    clf = RandomForestClassifier(max_depth=i, random_state=42)
    clf.fit(X_train, y_train)
    y_t = clf.predict(X_test)
    accuracy = accuracy_score(y_t,y_test)
    print("Accuracy: %.2f%%" % (accuracy * 100.0))
    
    

Accuracy: 39.58%
Accuracy: 58.33%
Accuracy: 63.19%
Accuracy: 73.61%
Accuracy: 73.61%
Accuracy: 75.69%
Accuracy: 77.08%
Accuracy: 80.56%
Accuracy: 81.94%
Accuracy: 81.94%
Accuracy: 81.25%
Accuracy: 81.25%
Accuracy: 81.25%
Accuracy: 80.56%
Accuracy: 80.56%
Accuracy: 81.25%
Accuracy: 81.94%
Accuracy: 81.94%
Accuracy: 81.25%
